default:
  workspace: shared

stages:
- Install

jobs:
- name: Fastlane Install
  stage: Install
  image: ruby:latest
  before_script:
  - gem install bundler
  - bundle install
  script: 
  - echo "Test CI"
  - ruby --version
  - bundle exec fastlane test
    