# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
opt_out_usage

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "upload to Beta by FireBase"
  lane :releaseApkByFirebase do
  firebase_app_distribution(
    app: "1:21101997881:android:e89e3e098342fed6a8c2e8",
    testers: “le.minh.hoang@sun-asterisk.com”,
    groups: “SunCI”,
    release_notes: "Version Staging",
    firebase_cli_path: "/usr/local/bin/firebase",
    service_credentials_file: './firebase-admin-sdk-key.json'
    )
end
end
